json.id @asistencium[:id]
json.nombre @asistencium[:nombre]
json.apellido @asistencium[:apellido]
json.correo @asistencium[:correo]
json.telefono @asistencium[:telefono]
json.institucion @asistencium[:institucion]
