json.id @propuestum[:id]
json.nombre @propuestum[:nombre]
json.titulo @propuestum[:titulo]
json.correo @propuestum[:correo]
json.organizacion @propuestum[:organizacion]
json.resumen @propuestum[:resumen]
json.reviser_id @propuestum[:reviser_id]
